AMI.AccessLog.Project/Models/Branch.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Branch
    {
        public Guid Id { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/Channel.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Channel
    {
        public Guid Id { get; set; }
        public string ChannelCode { get; set; }
        public string ChannelName { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/DailyActivity.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class DailyActivity
    {
        public Guid Id { get; set; }
        public string FinishedTask { get; set; }
        public string ContinueTask { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid UserId { get; set; }
    }
}

AMI.AccessLog.Project/Models/Department.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Department
    {
        public Guid Id { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/Device.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Device
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Ip { get; set; }
        public string Link { get; set; }
        public Guid? LocationId { get; set; }
        public string Remark { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/DeviceViewModel.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class DeviceViewModel
	{
        public Guid Id { get; set; }
        public string DeviceName { get; set; }
        public string Ip { get; set; }
        public string Link { get; set; }
		public string LocationName { get; set; }
        public string Remark { get; set; }
    }
}

AMI.AccessLog.Project/Models/IssueType.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class IssueType
    {
        public Guid Id { get; set; }
        public string IssueTypeCode { get; set; }
        public string IssueTypeName { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/Location.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Location
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/ServicePerson.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class ServicePerson
    {
        public Guid Id { get; set; }
        public string PersonId { get; set; }
        public string PersonName { get; set; }
        public Guid Position { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/ServiceStatus.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class ServiceStatus
    {
        public Guid Id { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/Team.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Team
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}

AMI.AccessLog.Project/Controllers/SetupController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AMI.AccessLog.Project.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using OfficeOpenXml;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.IO;

namespace AMI.AccessLog.Project.Controllers
{
    public class SetupController : Controller
    {
        AMI_ACCESSLOG_DBContext _db = new AMI_ACCESSLOG_DBContext();
        Common common = new Common();
        public ISession session;

        private IHostingEnvironment _env;

        public SetupController(IHostingEnvironment env)
        {
            _env = env;
        }

        #region ++ Device ++
		void GetViewBagDataForDevice()
		{
			ViewBag.DeviceList = (from t1 in _db.Device
								  join t2 in _db.Location on t1.LocationId equals t2.Id
								  orderby t1.Name
								  select new DeviceViewModel
								  {
									  Id = t1.Id,
									  DeviceName = t1.Name,
									  Ip = t1.Ip,
									  Link = t1.Link,
									  LocationName = t2.Name,
									  Remark = t1.Remark
								  }
			   ).ToList();
			ViewBag.LocationList = new SelectList(_db.Location.OrderBy(l => l.Name).ToList(), "Id", "Name");
		}
		public IActionResult Device(Device device)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			GetViewBagDataForDevice();
			return View(device);
		}

		bool CheckDevice(Device model)
		{
			if (model.Name == null || model.LocationId == Guid.Empty || model.LocationId == null)
			{
				TempData["Message"] = "*Please fill all the required fields";
				return false;
			}
			return true;
		}

		bool CheckForm(String name)
        {
            if (name == null)
            {
                TempData["Message"] = "*Please fill all the required fields";
                return false;
            }
            return true;
        }
        public IActionResult SaveDevice(Device device)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			if (device.Id == Guid.Empty)
            {
                bool check = CheckDevice(device);
                if (!check)
                {
					GetViewBagDataForDevice();
					return View("Device", device);
                }
                else
                {
                    device.Id = Guid.NewGuid();
					device.CreatedDate = DateTime.Now;
                    _db.Entry(device).State = EntityState.Added;
                    _db.SaveChanges();
                    TempData["Message"] = "Save Successful.";
                    return RedirectToAction("Device");
                }
            }
            else
            {
				bool check = CheckDevice(device);
				if (ModelState.IsValid && check == true)
                {
                    _db.Update(device);
                    _db.SaveChanges();
                    TempData["Message"] = "Update Successful.";
                    return RedirectToAction("Device");
                }
            }
			GetViewBagDataForDevice();
			return View("Device", device);
		}

		public IActionResult DeleteDevice(Guid deviceId)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			var device = _db.Device.AsNoTracking().SingleOrDefault(m => m.Id == deviceId);
            if (device == null)
            {
				GetViewBagDataForDevice();
				return View("Device");
			}

			try
            {
                var deviceList = _db.Register.Where(u => u.DeviceId == deviceId).ToList();
                if (deviceList.Count == 0)
                {
                    _db.Device.Remove(device);
                    _db.SaveChanges();
                    TempData["Message"] = "Delete Successful.";
                    return RedirectToAction("Device", new Device());
                }
                else
                {
                    TempData["Message"] = "This device has already used in process.";
                }
				GetViewBagDataForDevice();
				return View("Device", device);
			}
			catch (DbUpdateException)
            {
                return View("Device", new { id = deviceId, saveChangesError = true });
            }
        }

        public IActionResult EditDevice(Guid deviceId)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			Device device = _db.Device.Where(r => r.Id == deviceId).FirstOrDefault();
			GetViewBagDataForDevice();
			return View("Device", device);
		}

		public IActionResult ExportDeviceList()
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			var device_list = (from t1 in _db.Device
							   join t2 in _db.Location on t1.LocationId equals t2.Id
							   orderby t1.Name
							   select new DeviceViewModel
							   {
								   Id = t1.Id,
								   DeviceName = t1.Name,
								   Ip = t1.Ip,
								   Link = t1.Link,
								   LocationName = t2.Name,
								   Remark = t1.Remark
							   }
						   ).ToList(); ;

            var columnHeader = new List<string>
            {
                "Name",
                "IP",
                "Link",
				"Device Location",
				"Remark",
			};

            var fileContent = ExportExcelForDeviceList(device_list, columnHeader, "Device List");
            return File(fileContent, "application/ms-excel", "DeviceList.xlsx");
        }


        public byte[] ExportExcelForDeviceList(List<DeviceViewModel> device_list, List<string> columnHeader, string heading)
        {
            byte[] result = null;
            using (ExcelPackage package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add(heading);
                worksheet.DefaultColWidth = 20;
                using (var cells = worksheet.Cells[1, 1, 1, 8])
                {
                    cells.Style.Font.Bold = true;
                }

                for (int i = 0; i < columnHeader.Count(); i++)
                {
                    worksheet.Cells[1, i + 1].Value = columnHeader[i];
                }
                var j = 2;
                var count = 1;
                foreach (var item in device_list)
                {
                    worksheet.Cells["A" + j].Value = item.DeviceName;
                    worksheet.Cells["B" + j].Value = item.Ip;
                    worksheet.Cells["C" + j].Value = item.Link;
					worksheet.Cells["D" + j].Value = item.LocationName;
					worksheet.Cells["E" + j].Value = item.Remark;

                    j++;
                    count++;
                }
                result = package.GetAsByteArray();
            }
            return result;
        }


        #endregion

        public bool CheckLoginUser()
        {
            var userId = HttpContext.Session.GetString("userId");
            if (userId == null)
            {
                return false;
            }
            return true;

        }

        #region ++ Location ++
        public IActionResult Location(Location location)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			ViewBag.LocationList = _db.Location.OrderByDescending(l => l.Name).ToList();
            return View(location);
        }

        public IActionResult SaveLocation(Location location)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			if (location.Id == Guid.Empty)
            {
                bool check = CheckForm(location.Name);
                if (!check)
                {
					ViewBag.LocationList = _db.Location.OrderByDescending(l => l.Name).ToList();
					return View("Location", location);
                }
                else
                {
                    location.Id = Guid.NewGuid();
					location.CreatedDate = DateTime.Now;
                    _db.Entry(location).State = EntityState.Added;
                    _db.SaveChanges();
                    TempData["Message"] = "Save Successful.";
                    return RedirectToAction("Location");
                }
            }
            else
            {
                bool check = CheckForm(location.Name);
                if (ModelState.IsValid && check == true)
                {
                    _db.Update(location);
                    _db.SaveChanges();
                    TempData["Message"] = "Update Successful.";
                    return RedirectToAction("Location");
                }
            }
			ViewBag.LocationList = _db.Location.OrderByDescending(l => l.Name).ToList();
			return View("Location", location);
		}

		public IActionResult DeleteLocation(Guid locationId)
        {
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			var location = _db.Location.AsNoTracking().SingleOrDefault(m => m.Id == locationId);
            if (location == null)
            {
				ViewBag.LocationList = _db.Location.OrderByDescending(l => l.Name).ToList();
				return View("Location", location);
			}

			try
            {
                var locationList = _db.Device.Where(u => u.LocationId == locationId).ToList();
                if (locationList.Count == 0)
                {
                    _db.Location.Remove(location);
                    _db.SaveChanges();
                    TempData["Message"] = "Delete Successful.";
                    return RedirectToAction("Location", new Location());
                }
                else
                {
                    TempData["Message"] = "This location has already used in process.";
                }
				ViewBag.LocationList = _db.Location.OrderByDescending(l => l.Name).ToList();
				return View("Location", location);
			}
			catch (DbUpdateException)
            {
                return View("Location", new { id = locationId, saveChangesError = true });
            }
        }

        public IActionResult EditLocation(Guid locationId)
        {
			if (!CheckLoginUser())

AMI.AccessLog.Project/Views/Setup/Branch.cshtml
@model Branch
@{
    ViewData["Title"] = "Branch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

@using (Html.BeginForm("Branch", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="row">
    <div class="col-md-12">
        <h2 class="page-header">Branch</h2>
        @* <a href='@Url.Action("ExportBranchList","Setup", null)'>
                <img src="~/images/excel-file.png" style="float:right;color:#1e3f6d;" />
            </a>*@
        <ul class="nav navbar-right panel_toolbox" style="margin-right:20px;">

            <li class="dropdown" style="float:left;">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-file-excel-o" style="font-size:30px;"></i></a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href='@Url.Action("ExportBranchList", "Setup", null)'><i class="fa fa-download"></i> Export</a>
                    </li>
                    <li>
                        <a href="@Url.Action("ImportBranchList", "Setup")" id="btnImport"><i class="fa fa-upload"></i> Import</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.BranchCode)
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="wrap-input100 validate-input">
                <span class="label-input100">Branch Name:</span><span style="color:red;">*</span>
                @Html.TextBoxFor(model => model.BranchName, new { @class = "input100", @placeholder = "Enter Branch Name" })
                <span class="focus-input100"></span>
            </div>
        </div>

        <div class="col-md-3">
            <div class="wrap-input100 validate-input">
                <span class="label-input100">Address:</span>
                @*<input class="input100" type="text" name="Description" asp-for="Address" placeholder="Enter Description" id="desc">*@
                @Html.TextBoxFor(model => model.Address, new { @class = "input100", @placeholder = "Enter Address" })
                <span class="focus-input100"></span>
            </div>
        </div>

        <div class="col-md-3">
            <span class="label-input100">Active:</span>
            <div class="col-sm-1">@Html.CheckBoxFor(model => model.Active)</div>
        </div>

    </div>

    <div class="col-md-12">
        <div class="col-md-6">
            <div class="col-md-2">
                <a href='@Url.Action("Branch","Setup",null)' class="btn btn-default">
                    <i class="fa fa-plus"></i>
                    New
                </a>
            </div>
            <div class="col-md-2">
                <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                    <i class="fa fa-save"></i>
                    Save
                </button>
            </div>
            <div class="col-md-2">
                <a href='@Url.Action("DeleteBranch","Setup", new { @Id = Model.Id})' class="btn btn-default" onclick="return confirm('Are you sure you want to delete?')">
                    <i class="fa fa-trash"></i>
                    Delete
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <font color="red">@TempData["Message"]</font>
        </div>
    </div>

    <div class="col-md-12">
        <br />
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy">
                    <thead>
                        <tr>
                            <th>Branch Code</th>
                            <th>Branch Name</th>
                            <th>Address</th>
                            <th>Active</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var branch in (List<Branch>)ViewBag.BranchList)
                        {
                            <tr class="odd gradeX">
                                <td>@branch.BranchCode</td>
                                <td>@branch.BranchName</td>
                                <td>@branch.Address</td>
                                <td style="text-align:center;">@Html.CheckBox("chkActive", @branch.Active, new { @disabled = "disabled" })</td>
                                <td style="text-align:center;">
                                    <a href='@Url.Action("EditBranch", "Setup", new { @Id = @branch.Id })'>
                                        <img src="~/images/Edit.png" />
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
}

AMI.AccessLog.Project/Views/Setup/Channel.cshtml
@model Channel
@{
    ViewData["Title"] = "Channel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

@using (Html.BeginForm("SaveChannel", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-header">Channel</h2>
            @* <a href='@Url.Action("ExportBranchList","Setup", null)'>
                    <img src="~/images/excel-file.png" style="float:right;color:#1e3f6d;" />
                </a>*@
            <ul class="nav navbar-right panel_toolbox" style="margin-right:20px;">

                <li class="dropdown" style="float:left;">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-file-excel-o" style="font-size:30px;"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href='@Url.Action("ExportChannelList", "Setup", null)'><i class="fa fa-download"></i> Export</a>
                        </li>
                        <li>
                            <a href="@Url.Action("ImportChannelList", "Setup")" id="btnImport"><i class="fa fa-upload"></i> Import</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ChannelCode)
        <div class="col-md-12">
            <div class="col-md-3">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Channel Name:</span><span style="color:red;">*</span>
                    @Html.TextBoxFor(model => model.ChannelName, new { @class = "input100", @placeholder = "Enter Branch Name" })
                    <span class="focus-input100"></span>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="col-md-6">
                <div class="col-md-2">
                    <a href='@Url.Action("Channel","Setup",null)' class="btn btn-default">
                        <i class="fa fa-plus"></i>
                        New
                    </a>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                        <i class="fa fa-save"></i>
                        Save
                    </button>
                </div>
                <div class="col-md-2">
                    <a href='@Url.Action("DeleteChannel","Setup", new { @Id = Model.Id})' class="btn btn-default" onclick="return confirm('Are you sure you want to delete?')">
                        <i class="fa fa-trash"></i>
                        Delete
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <font color="red">@TempData["Message"]</font>
            </div>
        </div>
        <div class="col-md-12">
            <br />
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy">
                        <thead>
                            <tr>
                                <th>Channel Code</th>
                                <th>Channel Name</th>
                               
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var channel in (List<Channel>)ViewBag.ChannelList)
                            {
                                <tr class="odd gradeX">
                                    <td>@channel.ChannelCode</td>
                                    <td>@channel.ChannelName</td>
                                    <td style="text-align:center;">
                                        <a href='@Url.Action("EditChannel", "Setup", new { @Id = @channel.Id })'>
                                            <img src="~/images/Edit.png" />
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

AMI.AccessLog.Project/Views/Setup/DailyActivity.cshtml
@model AMI.AccessLog.Project.Models.DailyActivity

@{
    ViewData["Title"] = "DailyActivity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">
<style>
    .message-box {
        resize: none;
        width: 450px;
        min-height: 100px;
        padding: 5px;
        overflow: hidden;
        box-sizing: border-box;
    }
</style>
@using (Html.BeginForm("SaveDailyActivity", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-header">DailyActivity</h2>
            <a href='@Url.Action("ExportDailyActivityList","Report", null)'>
                    <img src="~/images/excel-file.png" style="float:right;color:#1e3f6d;" />
                </a>
        </div>
        <div class="col-md-12">
            <div class="col-md-2">
                <div class="wrap-input100 validate-input">
                    <label class="label-input100">Created Date:</label><span style="color:red;">*</span>
                    <input class="input100" type="date" name="CreatedDate" asp-for="CreatedDate">
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-4">
                <input type="hidden" asp-for="Id" />
                <div>
                    <label class="label-input100">Finished Tasks:</label><span style="color:red;">*</span>
                    <textarea class="form-control message-box" rows="8" name="FinishedTask" asp-for="FinishedTask" placeholder="Enter Finished Tasks" id="Finished"></textarea>
                </div>
            </div>
            <div class="col-md-1"></div>
                <div class="col-md-4">
                    <label class="label-input100">Continue Tasks:</label>
                    <textarea rows="8" class="form-control message-box" name="ContinueTask" asp-for="ContinueTask" placeholder="Enter Continue Tasks" id="Continue"></textarea>
                </div>
            </div>
        </div>
    <br /><br />
    <div class="col-md-12">
        <div class="col-md-6" style="margin-bottom:10px;">
            <div class="col-md-2">
                <a href='@Url.Action("DailyActivity","Setup", null)' class="btn btn-default">
                    <i class="fa fa-plus"></i>
                    New
                </a>
            </div>

            <div class="col-md-2">
                <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                    <i class="fa fa-save"></i>
                    Save
                </button>
            </div>
            <div class="col-md-2">
                <a href='@Url.Action("DeleteActivity","Setup", new {  @Id = Model.Id})' id="btnDelete" class="btn btn-default" onclick="return ConfirmDelete()">
                    <i class="fa fa-trash"></i>
                    Delete
                </a>

            </div>
        </div>
        <div class="col-md-6">
            <font color="red">@TempData["Message"]</font>
        </div>

    </div>
    <div class="col-md-12">
        <br />
        <div class="panel panel-default">
            <div class="panel-body">
                <table style="width: 100%;" class="table table-bordered" id="policy-datatable">
                    <thead>
                        <tr>
                            <th>Created Date<span class="caret"></span></th>
                            <th>Finished Tasks</th>
                            <th>ContinueTasks</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var activity in (List<DailyActivity>)ViewBag.DailyActivityList)
                        {
                        <tr class="odd gradeX">
                            <td>
                                @string.Format("{0:dd/MMM/yyyy}", activity.CreatedDate)
                            </td>

                            <td>
                                <textarea rows="8" cols="50" disabled style="background-color:#fff" id="finish"> @activity.FinishedTask</textarea>
                            </td>
                            <td><textarea rows="8" cols="50" disabled style="background-color:#fff">@activity.ContinueTask</textarea></td>
                            <td style="text-align:center;">
                                <a href='@Url.Action("EditActivity", "Setup", new { @Id = @activity.Id })'>
                                    <img src="~/images/Edit.png" />
                                </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

@section Scripts
    {
    <script type="text/javascript">
        function ConfirmDelete() {
            if (document.getElementById("Finished").value == "") {
                alert("Please select data to delete");
                return false;
            }
            else {
                return confirm("Are you sure you want to delete?");
            }
        }
        var table = $('#policy').DataTable();
    </script>
}

AMI.AccessLog.Project/Views/Setup/ImportBranchList.cshtml
@{
    ViewData["Title"] = "ImportBranchList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

@using (Html.BeginForm("ImportServiceStatusDataList", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">

        <h2 class="page-header">Branch</h2>

        <div class="col-md-4">
            <input type="file" id="reportfile" name="reportfile" class="form-control" />
        </div>
        <div class="col-md-8">
            <input type="submit" id="btnUpload" value="Upload" class="btn" style="color:#A92028;" />
        </div>
    </div>

}