AMI.AccessLog.Project/Models/ProjectStatus.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class ProjectStatus
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}

AMI.AccessLog.Project/Models/Status.cs
using System;
using System.Collections.Generic;

namespace AMI.AccessLog.Project.Models
{
    public partial class Status
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}

AMI.AccessLog.Project/Controllers/ProjectModuleController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using AMI.AccessLog.Project.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;

namespace AMI.AccessLog.Project.Controllers
{
    public class ProjectModuleController : Controller
    {
		AMI_ACCESSLOG_DBContext _db = new AMI_ACCESSLOG_DBContext();
		Common common = new Common();
		public ISession session;

		private IHostingEnvironment _env;

		public ProjectModuleController(IHostingEnvironment env)
		{
			_env = env;
		}

		#region ++ Project ++

		bool CheckProjectForm(ProjectData model)
		{
			if (model.Name == null || model.TeamId == null)
			{
				TempData["Message"] = "*Please fill all the required fields";
				return false;
			}
			return true;
		}

		public IActionResult ExportFinishedProject()
		{
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			var project_list = (from t1 in _db.ProjectData
								join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
								from subStatus in gj.DefaultIfEmpty()
								orderby t1.CreatedDate descending
								where t1.ProjectStatusId == Guid.Parse("62E18AAF-A16B-406B-84E8-BD99CCF85613")
								select new ProjectDataViewModel
								{
									Id = t1.Id,
									Name = t1.Name,
									StatusName = subStatus.Name ?? String.Empty,
									Description = t1.Description,
									CreatedDate = t1.CreatedDate
								}
				   ).ToList();

			var columnHeader = new List<string>
			{
				"Created Date",
				"Name",
				"Project Status",
				"Description",
			};

			var fileContent = ExportExcelForProjectList(project_list, columnHeader, "Finished Project List");
			return File(fileContent, "application/ms-excel", "Finished Project List.xlsx");
		}

        public IActionResult ExportTotalFinishedProject()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            var project_list = (from t1 in _db.ProjectData
                                join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
                                from subStatus in gj.DefaultIfEmpty()
                                orderby t1.CreatedDate descending
                                select new ProjectDataViewModel
                                {
                                    Id = t1.Id,
                                    Name = t1.Name,
                                    StatusName = subStatus.Name ?? String.Empty,
                                    Description = t1.Description,
                                    CreatedDate = t1.CreatedDate
                                }
                   ).ToList();

            var columnHeader = new List<string>
            {
                "Created Date",
                "Name",
                "Project Status",
                "Description",
            };

            var fileContent = ExportExcelForProjectList(project_list, columnHeader, "Total Project List");
            return File(fileContent, "application/ms-excel", "Total Project List.xlsx");
        }

        public IActionResult ExportDefinedFinishedProject()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

         
            var project_list = (from t1 in _db.ProjectData
                                   join t in _db.Team on t1.TeamId equals t.Id into b
                                   from sub in b.DefaultIfEmpty()
                                   join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
                                   from subStatus in gj.DefaultIfEmpty()
                                   where (t1.ProjectStatusId == null)
                                   select new ProjectDataViewModel
                                   {
                                       Id = t1.Id,
                                       Name = t1.Name,
                                       Team = sub.Name,
                                       StatusName = subStatus.Name ?? String.Empty,
                                       Description = t1.Description,
                                       CreatedDate = t1.CreatedDate
                                   }).ToList();

            var columnHeader = new List<string>
            {
                "Created Date",
                "Name",
                "Project Status",
                "Description",
            };

            var fileContent = ExportExcelForProjectList(project_list, columnHeader, "Underfined Project List");
            return File(fileContent, "application/ms-excel", "Underfined Project List.xlsx");
        }

        public IActionResult ExportProjectList()
		{
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			var project_list = (from t1 in _db.ProjectData
							   join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
							   from subStatus in gj.DefaultIfEmpty()
							   orderby t1.CreatedDate descending
								where t1.ProjectStatusId != Guid.Parse("62E18AAF-A16B-406B-84E8-BD99CCF85613")
								select new ProjectDataViewModel
							   {
								   Id = t1.Id,
								   Name = t1.Name,
								   StatusName = subStatus.Name ?? String.Empty,
								   Description = t1.Description,
								   CreatedDate = t1.CreatedDate
							   }
				   ).ToList();

			var columnHeader = new List<string>
			{
				"Created Date",
				"Name",
				"Project Status",
				"Description",
			};

			var fileContent = ExportExcelForProjectList(project_list, columnHeader, "Ongoing Project List");
			return File(fileContent, "application/ms-excel", "Ongoing Project List.xlsx");
		}

		public byte[] ExportExcelForProjectList(List<ProjectDataViewModel> project_list, List<string> columnHeader, string heading)
		{
			byte[] result = null;
			using (ExcelPackage package = new ExcelPackage())
			{
				var worksheet = package.Workbook.Worksheets.Add(heading);
				worksheet.DefaultColWidth = 20;
				using (var cells = worksheet.Cells[1, 1, 1, 8])
				{
					cells.Style.Font.Bold = true;
				}

				for (int i = 0; i < columnHeader.Count(); i++)
				{
					worksheet.Cells[1, i + 1].Value = columnHeader[i];
				}
				var j = 2;
				var count = 1;
				foreach (var item in project_list)
				{
					worksheet.Cells["A" + j].Value = item.CreatedDate.Value.ToString("dd/MMM/yyyy");
					worksheet.Cells["B" + j].Value = item.Name;
					worksheet.Cells["C" + j].Value = item.StatusName;
					worksheet.Cells["D" + j].Value = item.Description;

					j++;
					count++;
				}
				result = package.GetAsByteArray();
			}
			return result;
		}

		void GetViewBagDataForProject()
		{
			//62e18aaf - a16b - 406b - 84e8 - bd99ccf85613
			ViewBag.ProjectList = (from t1 in _db.ProjectData
								   join t in _db.Team on t1.TeamId equals t.Id into b
								   from sub in b.DefaultIfEmpty()
								   join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
								   from subStatus in gj.DefaultIfEmpty()
								   orderby t1.CreatedDate descending
								   where t1.ProjectStatusId != Guid.Parse("62E18AAF-A16B-406B-84E8-BD99CCF85613")
								   select new ProjectDataViewModel
								   {
									   Id = t1.Id,
									   Name = t1.Name,
									   Team = sub.Name,
									   StatusName = subStatus.Name ?? String.Empty,
									   Description = t1.Description,
									   CreatedDate = t1.CreatedDate
								   }).ToList();
			ViewBag.TeamList = new SelectList(_db.Team.OrderBy(t => t.Name).ToList(), "Id", "Name");
			ViewBag.ProjectStatusList = new SelectList(_db.ProjectStatus.OrderBy(P => P.Name).ToList(), "Id", "Name");
		}

		public IActionResult Project(ProjectData project)
		{
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			GetViewBagDataForProject();
			return View(project);
		}

		public IActionResult FinishedProject(ProjectData project)
		{
			if (!CheckLoginUser())
				return RedirectToAction("Login", "Account");

			ViewBag.ProjectList = (from t1 in _db.ProjectData
								   join t in _db.Team on t1.TeamId equals t.Id into b
								   from sub in b.DefaultIfEmpty()
								   join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
								   from subStatus in gj.DefaultIfEmpty()
								   where t1.ProjectStatusId == Guid.Parse("62E18AAF-A16B-406B-84E8-BD99CCF85613")
                                   orderby t1.CreatedDate descending
								   select new ProjectDataViewModel
								   {
									   Id = t1.Id,
									   Name = t1.Name,
									   Team = sub.Name,
									   StatusName = subStatus.Name ?? String.Empty,
									   Description = t1.Description,
									   CreatedDate = t1.CreatedDate
								   }).ToList();
			ViewBag.TeamList = new SelectList(_db.Team.OrderBy(t => t.Name).ToList(), "Id", "Name");
			ViewBag.ProjectStatusList = new SelectList(_db.ProjectStatus.OrderBy(P => P.Name).ToList(), "Id", "Name");
			return View(project);
		}

        public IActionResult TotalProject(ProjectData project)
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            ViewBag.ProjectList = (from t1 in _db.ProjectData
                                   join t in _db.Team on t1.TeamId equals t.Id into b
                                   from sub in b.DefaultIfEmpty()
                                   join t2 in _db.ProjectStatus on t1.ProjectStatusId equals t2.Id into gj
                                   from subStatus in gj.DefaultIfEmpty()
                                   orderby t1.CreatedDate descending
                                   select new ProjectDataViewModel
                                   {
                                       Id = t1.Id,

AMI.AccessLog.Project/Views/ProjectModule/FinishedProject.cshtml
@model AMI.AccessLog.Project.Models.ProjectData
@{
    ViewData["Title"] = "FinishedProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

@using (Html.BeginForm("SaveProject", "ProjectModule", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-header">Finished Project</h2>
            <a href='@Url.Action("ExportFinishedProject","ProjectModule", null)'>
                <img src="~/images/excel-file.png" style="float:right;color:#1e3f6d;" />
            </a>
        </div>
        @Html.HiddenFor(model => model.Id)
        <div class="col-md-12">
            <br />
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy-datatable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Created Date <span class="caret"></span></th>
                                <th>Name</th>
                                <th>Related Team</th>
                                <th>Project Status</th>
                                <th>Description</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int rowNo = 0; }
                            @foreach (var project in (List<ProjectDataViewModel>)ViewBag.ProjectList)
                            {
                            <tr class="odd gradeX">
                                <td>
                                    @(rowNo += 1)
                                </td>
                                <td>@string.Format("{0:dd/MMM/yyyy}", project.CreatedDate)</td>
                                <td>@project.Name</td>
                                <td>@project.Team</td>
                                <td>@project.StatusName</td>
                                <td>@project.Description</td>
                                <td style="text-align:center;">
                                    <a href='@Url.Action("EditProject", "ProjectModule", new { @projectId = @project.Id })'>
                                        <img src="~/images/Edit.png" />
                                    </a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts
    {
    <script type="text/javascript">
        function ConfirmDelete() {
            if (document.getElementById("name").value == "" && document.getElementById("desc").value == "" && document.getElementById("status").value == "") {
                alert("Please select data to delete");
                return false;
            }
            else {
                return confirm("Are you sure you want to delete?");
            }
        }
    </script>
}

AMI.AccessLog.Project/Views/ProjectModule/ItemsListForStaff.cshtml
@model AMI.AccessLog.Project.Models.RequirementItems
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Items List For Staff";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

@using (Html.BeginForm("SaveItemsForStaff", "ProjectModule", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-header"> Requirement Items List </h2>
            <a href='@Url.Action("ExportItemsListForStaff","ProjectModule", new { UserId =Guid.Parse(HttpContextAccessor.HttpContext.Session.GetString("userId"))  })'>
                <img src="~/images/excel-file.png" style="float:right;color:#1e3f6d;" />
            </a>
        </div>
        @Html.HiddenFor(model => model.Id)
        @*<input type="hidden" name="Date" asp-for="Date" value="@Model.Date">*@
        @*<input type="hidden" name="Date" asp-for="Date" value="@Model.Date">
        <input type="hidden" name="Description" asp-for="Description" value="@Model.Description">
        <input type="hidden" name="ProjectId" asp-for="ProjectId" value="@Model.ProjectId">
        <input type="hidden" name="ImplementTechnicianId" asp-for="ImplementTechnicianId" value="@Model.ImplementTechnicianId">
        <input type="hidden" name="CheckTechnicianId" asp-for="CheckTechnicianId" value="@Model.CheckTechnicianId">*@
        <div class="col-md-12">
            <div class="col-md-2">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Created Date:</span><span style="color:red;">*</span>
                    <input class="input100" type="date" name="Date" asp-for="Date">
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Requirement Item:</span><span style="color:red;">*</span>
                    <input class="input100" type="text" name="Description" asp-for="Description" placeholder="Enter Description" id="description">
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100"> Project Name:</span><span style="color:red;">*</span>
                    <div id="Staff" required>
                        @Html.DropDownListFor(model => model.ProjectId, ViewBag.ProjectList as IEnumerable<SelectListItem>, "Select Project", new { @class = "input100", @id = "project", @style = "border:none;margin-top:9px;" })
                    </div>
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-2">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Start Date:</span>
                    <input class="input100" type="date" name="StartDate" asp-for="StartDate" value="@string.Format("{0:yyyy-MM-dd}", Model.StartDate)">
                    @*<input class="input100" type="date" name="StartDate" asp-for="StartDate" id="StartDate" value="@Model.StartDate">*@
                    @*<input class="input100" type="date" name="fromDate" asp-for="fromDate" id="fromDate" value="" >*@
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-2">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">End Date:</span>
                    <input class="input100" type="date" name="EndDate" asp-for="EndDate" value="@string.Format("{0:yyyy-MM-dd}", Model.EndDate)">
                    @*<input class="input100" type="date" name="toDate" asp-for="toDate" id="toDate" value="">*@
                    <span class="focus-input100"></span>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-2">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Status:</span>
                    <div id="Staff" required>
                        @Html.DropDownListFor(model => model.StatusId, ViewBag.StatusList as IEnumerable<SelectListItem>, "Select Status", new { @class = "input100", @id = "status", @style = "border:none;margin-top:9px;" })
                    </div>
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100"> Assign / Implement Technician:</span><span style="color:red;">*</span>
                    <div id="Staff" required>
                        @Html.DropDownListFor(model => model.ImplementTechnicianId, ViewBag.UserList as IEnumerable<SelectListItem>, "Select Technician", new { @class = "input100", @id = "implement", @style = "border:none;margin-top:9px;" })
                    </div>
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100"> Assign / Check Technician:</span><span style="color:red;">*</span>
                    <div id="Staff" required>
                        @Html.DropDownListFor(model => model.CheckTechnicianId, ViewBag.UserList as IEnumerable<SelectListItem>, "Select Technician", new { @class = "input100", @id = "check", @style = "border:none;margin-top:9px;" })
                    </div>
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-2">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Remark:</span>
                    <input class="input100" type="text" name="Remark" asp-for="Remark" placeholder="Enter Remark" id="remark">
                    <span class="focus-input100"></span>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <div class="col-md-2">
                    <a href='@Url.Action("ItemsListForStaff","ProjectModule",  null)' class="btn btn-default">
                        <i class="fa fa-plus"></i>
                        New
                    </a>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                        <i class="fa fa-save"></i>
                        Save
                    </button>
                </div>
                 <div class="col-md-2">
                    <a href='@Url.Action("DeleteItem","ProjectModule", new { @itemId = Model.Id})' id="btnDelete" class="btn btn-default" onclick="return ConfirmDelete()">
                        <i class="fa fa-trash"></i>
                        Delete
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <font color="red">@TempData["Message"]</font>
            </div>
        </div>
        <div class="col-md-12">
            <br />
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy-datatable">
                        <thead>
                            <tr>
                                <th>Date<span class="caret"></span></th>
                                <th>Requirement Item</th>
                                <th>Project Name</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Assign/Implement Technician</th>
                                <th>Assign/Check Technician</th>
                                <th>Status Name</th>
                                <th>Remark</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var items in (List<RequirementItemsViewModel>)ViewBag.ItemsList)
                            {
                                <tr class="odd gradeX">
                                    @*<td>@items.Date</td>*@
                                    <td>@string.Format("{0:dd/MMM/yyyy}", items.Date)</td>
                                    <td>@items.Description</td>
                                    <td>@items.ProjectName</td>
                                    @if (items.StartDate == null)
                                    {
                                        <td>@items.StartDate</td>
                                    }
                                    else
                                    {
                                        @*<td>@items.StartDate.Value.ToShortDateString()</td>*@
                                        //<td>@items.StartDate.Value.Date</td>
                                        <td>@items.StartDate.Value.ToString("dd-MM-yyyy")</td>
                                    }
                                    @if (items.EndDate == null)
                                    {
                                        <td>@items.EndDate</td>
                                    }
                                    else
                                    {
                                        @*<td>@items.EndDate.Value.ToShortDateString()</td>*@
                                        <td>@items.EndDate.Value.ToString("dd-MM-yyyy")</td>
                                    }
                                    <td>@items.ImplementTechnicianName</td>
                                    <td>@items.CheckTechnicianName</td>
                                    <td>@items.StatusName</td>
                                    <td>@items.Remark</td>
                                    <td style="text-align:center;">
                                        <a href='@Url.Action("EditItemForStaff", "ProjectModule", new { @itemId = @items.Id })'>
                                            <img src="~/images/Edit.png" />
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts
    {
    <script type="text/javascript">
        function ConfirmDelete() {
            if (document.getElementById("description").value == "" && document.getElementById("project").value == ""
                && document.getElementById("implement").value == "" && document.getElementById("check").value == "" && document.getElementById("status").value == "") {
                alert("Please select data to delete");
                return false;
            }
            else {
                return confirm("Are you sure you want to delete?");
            }
        }
    </script>
}

AMI.AccessLog.Project/Views/ProjectModule/ProjectStatus.cshtml
@model AMI.AccessLog.Project.Models.ProjectStatus
@{
    ViewData["Title"] = "ProjectStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/css/util.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

@using (Html.BeginForm("SaveProjectStatus", "ProjectModule", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 class="page-header">Project Status</h2>
            <a href='@Url.Action("ExportProjectStatusList","ProjectModule", null)'>
                <img src="~/images/excel-file.png" style="float:right;color:#1e3f6d;" />
            </a>
        </div>
        @Html.HiddenFor(model => model.Id)
        <div class="col-md-12">
            <div class="col-md-4">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Status Name:</span><span style="color:red;">*</span>
                    <input class="input100" type="text" name="Name" asp-for="Name" placeholder="Enter Name" id="name">
                    <span class="focus-input100"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="wrap-input100 validate-input">
                    <span class="label-input100">Description:</span>
                    <input class="input100" type="text" name="Description" asp-for="Description" placeholder="Enter Description" id="desc">
                    <span class="focus-input100"></span>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <div class="col-md-2">
                    <a href='@Url.Action("ProjectStatus","ProjectModule", null)' class="btn btn-default">
                        <i class="fa fa-plus"></i>
                        New
                    </a>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-default" id="btnSave" type="submit" onclick="return confirm('Are you sure you want to save?')">
                        <i class="fa fa-save"></i>
                        Save
                    </button>
                </div>
                <div class="col-md-2">
                    <a href='@Url.Action("DeleteProjectStatus","ProjectModule", new { @statusId = Model.Id})' id="btnDelete" class="btn btn-default" onclick="return ConfirmDelete()">
                        <i class="fa fa-trash"></i>
                        Delete
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <font color="red">@TempData["Message"]</font>
            </div>
        </div>
        <div class="col-md-12">
            <br />
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table style="width: 100%;" class="table table-striped table-bordered table-hover" id="policy">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var status in (List<ProjectStatus>)ViewBag.ProjectStatusList)
                            {
                                <tr class="odd gradeX">
                                    <td>@status.Name</td>
                                    <td>@status.Description</td>
                                    <td style="text-align:center;">
                                        <a href='@Url.Action("EditProjectStatus", "ProjectModule", new { @statusId = @status.Id })'>
                                            <img src="~/images/Edit.png" />
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts
    {
    <script type="text/javascript">
        function ConfirmDelete() {
            if (document.getElementById("name").value == "" && document.getElementById("desc").value == "") {
                alert("Please select data to delete");
                return false;
            }
            else {
                return confirm("Are you sure you want to delete?");

            }
        }
        var table = $('#policy').DataTable();
        table.order([0, 'asc']).draw();
    </script>
}